// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Azure/rate-limiter/ratelimiter (interfaces: RateLimiter)

// Package mock_ratelimiter is a generated GoMock package.
package mock_ratelimiter

import (
	context "context"
	reflect "reflect"
	time "time"

	"go.uber.org/mock/gomock"
)

// MockRateLimiter is a mock of RateLimiter interface.
type MockRateLimiter struct {
	ctrl     *gomock.Controller
	recorder *MockRateLimiterMockRecorder
}

// MockRateLimiterMockRecorder is the mock recorder for MockRateLimiter.
type MockRateLimiterMockRecorder struct {
	mock *MockRateLimiter
}

// NewMockRateLimiter creates a new mock instance.
func NewMockRateLimiter(ctrl *gomock.Controller) *MockRateLimiter {
	mock := &MockRateLimiter{ctrl: ctrl}
	mock.recorder = &MockRateLimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRateLimiter) EXPECT() *MockRateLimiterMockRecorder {
	return m.recorder
}

// GetDecision mocks base method.
func (m *MockRateLimiter) GetDecision(arg0 context.Context, arg1 string, arg2 int, arg3 time.Duration) (time.Duration, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDecision", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDecision indicates an expected call of GetDecision.
func (mr *MockRateLimiterMockRecorder) GetDecision(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDecision", reflect.TypeOf((*MockRateLimiter)(nil).GetDecision), arg0, arg1, arg2, arg3)
}
